services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: galton_backend
    ports:
      - 8080:8080
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: galton_frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
